"""S2's three enum types and its two tables, plus six delta-cursor indexes.

The types come first, because the tables declare them: `devices.status` is a
`device_status` column and not a varchar that happens to hold one of two words.
**`sync_conflict_type` is created with every value it will ever hold** --
including `negative_stock`, which S3 writes, and `stale_price` and
`catalog_divergence`, which S4 writes. No later stage runs `ALTER TYPE`: a value
added by the stage that writes it is a migration that has to land before the
stage that reads it, which is a coordination bug waiting for a clean build
(ownership.md, enum register).

The six indexes land on tables S2 does not own, under ledger rule 4 -- the index
belongs to the stage whose read path needs it, and the read path is
`GET /api/sync/pull`. The seventh index that path needs,
`customers (tenant_id, document_type, document) WHERE document <> ''`, already
exists: S1 created it as `one_customer_per_document_per_tenant`, and rule 4 says
an index is created once by the first stage that needs it and inherited by every
later one. S2 inherits it and declares it as the push's natural key instead of
migrating a duplicate that would fail on a clean build.

The RLS policies live in 0008, so that the security layer stays one file
somebody can read in SQL -- the same split S0 took between 0001 and 0002 and S1
between 0005 and 0006.
"""

# Generated by Django 6.1 on 2026-09-02 09:59

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


ENUMS = r"""
CREATE TYPE device_status AS ENUM ('active', 'revoked');

-- Every value, declared once, at creation. Six are S2's own protocol
-- refusals; `negative_stock` is S3's and the last two are S4's.
CREATE TYPE sync_conflict_type AS ENUM (
    'foreign_tenant',
    'foreign_location',
    'unknown_collection',
    'payload_rejected',
    'device_revoked',
    'device_silent',
    'negative_stock',
    'stale_price',
    'catalog_divergence'
);

-- `dismissed` exists because an administrator must be able to close a row
-- without claiming a correction was made.
CREATE TYPE sync_conflict_status AS ENUM ('open', 'resolved', 'dismissed');
"""

ENUMS_REVERSE = r"""
DROP TYPE sync_conflict_status;
DROP TYPE sync_conflict_type;
DROP TYPE device_status;
"""



class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_catalog_rls"),
    ]

    operations = [
        migrations.RunSQL(sql=ENUMS, reverse_sql=ENUMS_REVERSE),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=60)),
                ("code", models.CharField(max_length=16)),
                ("device_key_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    core.models.EnumField(
                        choices=[("active", "Activo"), ("revoked", "Dado de baja")],
                        db_enum="device_status",
                        default="active",
                        max_length=16,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("clock_skew_ms", models.IntegerField(blank=True, null=True)),
                ("storage_persisted", models.BooleanField(blank=True, null=True)),
                ("app_version", models.CharField(blank=True, max_length=32)),
                (
                    "enrolled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "devices",
                "ordering": ["location__name", "label"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("collection", models.CharField(blank=True, max_length=64)),
                ("client_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "type",
                    core.models.EnumField(
                        choices=[
                            ("foreign_tenant", "Fila de otra droguería"),
                            ("foreign_location", "Fila de otra sede"),
                            ("unknown_collection", "Colección desconocida"),
                            ("payload_rejected", "Datos rechazados"),
                            ("device_revoked", "Equipo dado de baja"),
                            ("device_silent", "Equipo sin sincronizar"),
                            ("negative_stock", "Existencias en negativo"),
                            ("stale_price", "Precio desactualizado"),
                            ("catalog_divergence", "Catálogo divergente"),
                        ],
                        db_enum="sync_conflict_type",
                        max_length=32,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    core.models.EnumField(
                        choices=[
                            ("open", "Abierto"),
                            ("resolved", "Resuelto"),
                            ("dismissed", "Descartado"),
                        ],
                        db_enum="sync_conflict_status",
                        default="open",
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
            ],
            options={
                "db_table": "sync_conflicts",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["tenant", "updated_at", "id"], name="categories_delta_cursor"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "updated_at", "id"], name="customers_delta_cursor"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["tenant", "updated_at", "id"], name="items_delta_cursor"
            ),
        ),
        migrations.AddIndex(
            model_name="itembarcode",
            index=models.Index(
                fields=["tenant", "updated_at", "id"], name="item_barcodes_delta_cursor"
            ),
        ),
        migrations.AddIndex(
            model_name="itemprice",
            index=models.Index(
                fields=["tenant", "location", "updated_at", "id"],
                name="item_prices_delta_cursor",
            ),
        ),
        migrations.AddIndex(
            model_name="manufacturer",
            index=models.Index(
                fields=["tenant", "updated_at", "id"], name="manufacturers_delta_cursor"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="enrolled_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="revoked_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.device",
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="resolved_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncconflict",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("tenant", "location", "label"),
                name="one_device_label_per_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="one_device_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "revoked"])),
                name="device_status_is_declared",
            ),
        ),
        migrations.AddIndex(
            model_name="syncconflict",
            index=models.Index(
                fields=["tenant", "status", "-recorded_at"], name="sync_conflicts_queue"
            ),
        ),
        migrations.AddConstraint(
            model_name="syncconflict",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "resolved", "dismissed"])),
                name="sync_conflict_status_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncconflict",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "foreign_tenant",
                            "foreign_location",
                            "unknown_collection",
                            "payload_rejected",
                            "device_revoked",
                            "device_silent",
                            "negative_stock",
                            "stale_price",
                            "catalog_divergence",
                        ],
                    )
                ),
                name="sync_conflict_type_is_declared",
            ),
        ),
    ]
