"""S4's four enum types and its six tables.

**Four `CREATE TYPE` and no `ALTER TYPE` anywhere in this stage** (ownership.md,
enum register). Two of the four are the ledger's -- `sale_status` and
`sale_source` -- and two are coined here: `shift_status`, because §3 gives
`shifts.status` a column and the register gives it no values, and
`payment_method`, whose five values are §3's verbatim and whose name is new.

`sale_source` is created complete with `imported`, which **S6** writes and S4
never does. A value migrated by the stage that writes it would have to land
before the stage that reads it, which fails a clean build in dependency order
rather than at the write -- the same reasoning S2 applied to `sync_conflict_type`
and S3 to `stock_move_type`.

**`sync_conflict_type` is not touched here, and the *Verification* gate that asks
for `stale_price` and `catalog_divergence` in a migration of their own is already
satisfied.** S2 declared both at creation in migration 0007, ahead of every line
of code that writes them, which is the property the gate is about: Postgres will
not let a value be used in the transaction that adds it, and Django's migrations
are atomic.

The RLS policies live in 0012, so the security layer stays one file somebody can
read in SQL -- the same split S0 took between 0001 and 0002, S1 between 0005 and
0006, S2 between 0007 and 0008 and S3 between 0009 and 0010.
"""

# Generated by Django 6.1 on 2026-09-02 19:22

import core.models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

ENUM = r"""
CREATE TYPE shift_status AS ENUM ('open', 'closed');

-- `voided` is here at creation and not added later: a sale is voided by the
-- cashier who rang it inside their own turno, which is a client write on the
-- ordinary push path, and a type that gained the value in a later migration
-- would be a coordination bug waiting for a clean build.
CREATE TYPE sale_status AS ENUM ('open', 'closed', 'voided');

-- `imported` is **S6's** and S4 writes it nowhere. Declaring a value is not
-- writing one.
CREATE TYPE sale_source AS ENUM ('counter', 'imported');

-- §3's five, verbatim and in the order the payment dialog renders them.
CREATE TYPE payment_method AS ENUM (
    'cash',
    'debit_card',
    'credit_card',
    'transfer',
    'other'
);
"""

ENUM_REVERSE = r"""
DROP TYPE payment_method;
DROP TYPE sale_source;
DROP TYPE sale_status;
DROP TYPE shift_status;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_inventory_rls"),
    ]

    operations = [
        # First, and before any table that names one of them.
        migrations.RunSQL(sql=ENUM, reverse_sql=ENUM_REVERSE),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField()),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("number", models.CharField(max_length=32)),
                (
                    "status",
                    core.models.EnumField(
                        choices=[
                            ("open", "Abierta"),
                            ("closed", "Cerrada"),
                            ("voided", "Anulada"),
                        ],
                        db_enum="sale_status",
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    core.models.EnumField(
                        choices=[
                            ("counter", "Mostrador"),
                            ("imported", "Historial cargado"),
                        ],
                        db_enum="sale_source",
                        default="counter",
                        max_length=16,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("sold_by_name", models.CharField(blank=True, max_length=200)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="core.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.device",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.location",
                    ),
                ),
                (
                    "sold_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "sales",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField()),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("position", models.PositiveIntegerField()),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_class",
                    core.models.EnumField(
                        choices=[
                            ("excluded", "Excluido de IVA"),
                            ("exempt", "Exento de IVA"),
                            ("rate_5", "IVA 5%"),
                            ("rate_19", "IVA 19%"),
                        ],
                        db_enum="vat_class",
                        max_length=16,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("from_suggestion", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.device",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.location",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.lot",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "sale_lines",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField()),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("number", models.CharField(max_length=32)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.TextField()),
                (
                    "refund_method",
                    core.models.EnumField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("debit_card", "Débito"),
                            ("credit_card", "Crédito"),
                            ("transfer", "Transferencia"),
                            ("other", "Otro"),
                        ],
                        db_enum="payment_method",
                        max_length=16,
                    ),
                ),
                ("returned_by_name", models.CharField(blank=True, max_length=200)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.device",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.location",
                    ),
                ),
                (
                    "returned_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="core.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "sale_returns",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField()),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_class",
                    core.models.EnumField(
                        choices=[
                            ("excluded", "Excluido de IVA"),
                            ("exempt", "Exento de IVA"),
                            ("rate_5", "IVA 5%"),
                            ("rate_19", "IVA 19%"),
                        ],
                        db_enum="vat_class",
                        max_length=16,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.device",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.location",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.lot",
                    ),
                ),
                (
                    "sale_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.saleline",
                    ),
                ),
                (
                    "sale_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.salereturn",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "sale_return_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField()),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("user_name", models.CharField(blank=True, max_length=200)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opening_float",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "declared_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    core.models.EnumField(
                        choices=[("open", "Abierto"), ("closed", "Cerrado")],
                        db_enum="shift_status",
                        default="open",
                        max_length=16,
                    ),
                ),
                ("forced_close_reason", models.TextField(blank=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.device",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shifts",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="salereturn",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returns",
                to="core.shift",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="core.shift",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_uuid", models.UUIDField()),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "method",
                    core.models.EnumField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("debit_card", "Débito"),
                            ("credit_card", "Crédito"),
                            ("transfer", "Transferencia"),
                            ("other", "Otro"),
                        ],
                        db_enum="payment_method",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reference", models.CharField(blank=True, max_length=64)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.device",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.sale",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["method"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "location", "updated_at", "id"],
                        name="payments_delta_cursor",
                    ),
                    models.Index(fields=["tenant", "sale"], name="payments_by_sale"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "client_uuid"),
                        name="one_payment_per_client_uuid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "method__in",
                                [
                                    "cash",
                                    "debit_card",
                                    "credit_card",
                                    "transfer",
                                    "other",
                                ],
                            )
                        ),
                        name="payment_method_is_declared",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="a_payment_pays_something",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="saleline",
            index=models.Index(
                fields=["tenant", "location", "updated_at", "id"],
                name="sale_lines_delta_cursor",
            ),
        ),
        migrations.AddIndex(
            model_name="saleline",
            index=models.Index(fields=["tenant", "sale"], name="sale_lines_by_sale"),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_uuid"), name="one_sale_line_per_client_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sale", "position"),
                name="one_line_per_position_per_sale",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="a_sale_line_sells_something",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vat_class__in", ["excluded", "exempt", "rate_5", "rate_19"])
                ),
                name="sale_line_vat_class_is_declared",
            ),
        ),
        migrations.AddIndex(
            model_name="salereturnline",
            index=models.Index(
                fields=["tenant", "location", "updated_at", "id"],
                name="return_lines_delta_cursor",
            ),
        ),
        migrations.AddIndex(
            model_name="salereturnline",
            index=models.Index(
                fields=["tenant", "sale_return"], name="return_lines_by_return"
            ),
        ),
        migrations.AddIndex(
            model_name="salereturnline",
            index=models.Index(
                fields=["tenant", "sale_line"], name="return_lines_by_line"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_uuid"), name="one_return_line_per_client_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sale_return", "sale_line"),
                name="one_return_line_per_original_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="a_return_line_returns_something",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vat_class__in", ["excluded", "exempt", "rate_5", "rate_19"])
                ),
                name="return_line_vat_class_is_declared",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["tenant", "location", "updated_at", "id"],
                name="shifts_delta_cursor",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["tenant", "location", "-opened_at"], name="shifts_office_list"
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_uuid"), name="one_shift_per_client_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("tenant", "device"),
                name="one_open_shift_per_device",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "closed"])),
                name="shift_status_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("closed_at__isnull", True), ("status", "open")),
                    models.Q(("closed_at__isnull", False), ("status", "closed")),
                    _connector="OR",
                ),
                name="a_closed_shift_has_a_close",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("declared_total__isnull", True), ("variance__isnull", True)
                    ),
                    models.Q(
                        ("declared_total__isnull", False), ("variance__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="a_declared_total_carries_its_variance",
            ),
        ),
        migrations.AddIndex(
            model_name="salereturn",
            index=models.Index(
                fields=["tenant", "location", "updated_at", "id"],
                name="sale_returns_delta_cursor",
            ),
        ),
        migrations.AddIndex(
            model_name="salereturn",
            index=models.Index(fields=["tenant", "sale"], name="sale_returns_by_sale"),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_uuid"), name="one_return_per_client_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.UniqueConstraint(
                fields=("tenant", "location", "number"),
                name="one_return_number_per_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "refund_method__in",
                        ["cash", "debit_card", "credit_card", "transfer", "other"],
                    )
                ),
                name="refund_method_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="a_return_states_its_reason",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["tenant", "location", "updated_at", "id"],
                name="sales_delta_cursor",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["tenant", "location", "recorded_at"],
                name="sales_location_period",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["tenant", "shift"], name="sales_by_shift"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                condition=models.Q(("source", "counter"), ("status", "open")),
                fields=["tenant", "location"],
                name="sales_open_at_the_counter",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_uuid"), name="one_sale_per_client_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("tenant", "location", "number"),
                name="one_sale_number_per_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "counter"), _negated=True),
                    ("shift__isnull", False),
                    _connector="OR",
                ),
                name="a_counter_sale_sits_in_a_shift",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "closed", "voided"])),
                name="sale_status_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["counter", "imported"])),
                name="sale_source_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("subtotal"), "-", models.F("discount")
                        ),
                    )
                ),
                name="a_total_is_its_subtotal_less_its_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax__lte", models.F("total"))),
                name="tax_is_contained_in_the_total",
            ),
        ),
    ]
