"""S5's one enum type and its one table, plus one index migrated onto S4's.

**One `CREATE TYPE` and no `ALTER TYPE`** (ownership.md, enum register).
`fiscal_document_status` is the ledger's, with its four values declared at
creation: they describe **our handoff** to the client's invoicing system and not
the DIAN's filing (architecture §8, A9). There is no `accepted`, no `rejected`
and no `contingency` -- Botica never learns what the DIAN did with a document,
so a value naming that outcome would be a value no code path could ever honestly
write.

**The partial index on `sales` is rule 4's exception to rule 1**: an index
belongs to the stage whose read path needs it, and the read path is the orphan
check -- a closed counter sale holding no `fiscal_documents` row after the
target's `configured_at`. It reverses with this migration, so S5 rolls back on
its own without leaving a stranger's index on S4's table.

The RLS policy lives in 0014, so the security layer stays one file somebody can
read in SQL -- the same split S0 took between 0001 and 0002, S1 between 0005 and
0006, S2 between 0007 and 0008, S3 between 0009 and 0010 and S4 between 0011 and
0012.
"""

# Generated by Django 6.1 on 2026-09-03 09:22

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


ENUM = r"""
-- The ledger's four, declared complete. They are a statement about **our
-- handoff** and never about the DIAN: `acknowledged` says the client's own
-- invoicing system holds the document and stops there.
CREATE TYPE fiscal_document_status AS ENUM (
    'pending',
    'sent',
    'acknowledged',
    'failed'
);
"""

ENUM_REVERSE = r"""
DROP TYPE fiscal_document_status;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_counter_rls"),
    ]

    operations = [
        # First, and before any table that names it.
        migrations.RunSQL(sql=ENUM, reverse_sql=ENUM_REVERSE),
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_key", models.CharField(max_length=96)),
                ("target", models.CharField(max_length=32)),
                ("mapping_version", models.CharField(blank=True, max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    core.models.EnumField(
                        choices=[
                            ("pending", "Pendiente de envío"),
                            ("sent", "Enviado"),
                            ("acknowledged", "Confirmado"),
                            ("failed", "Falló el envío"),
                        ],
                        db_enum="fiscal_document_status",
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("external_number", models.CharField(blank=True, max_length=64)),
                ("cude", models.CharField(blank=True, max_length=128)),
                ("pdf_url", models.TextField(blank=True)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "fiscal_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                condition=models.Q(("source", "counter"), ("status", "closed")),
                fields=["tenant", "recorded_at"],
                name="sales_closed_for_handoff",
            ),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="core.sale",
            ),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="sale_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="core.salereturn",
            ),
        ),
        migrations.AddField(
            model_name="fiscaldocument",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscaldocument",
            index=models.Index(
                condition=models.Q(("status__in", ("pending", "sent", "failed"))),
                fields=["tenant", "status", "next_attempt_at"],
                name="fiscal_documents_due",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscaldocument",
            index=models.Index(
                fields=["tenant", "location", "status", "-created_at"],
                name="fiscal_documents_list",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscaldocument",
            index=models.Index(
                fields=["tenant", "sale"], name="fiscal_documents_by_sale"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.UniqueConstraint(
                fields=("tenant", "document_key"), name="one_document_per_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sale__isnull", False), ("sale_return__isnull", True)),
                    models.Q(("sale__isnull", True), ("sale_return__isnull", False)),
                    _connector="OR",
                ),
                name="a_document_names_a_sale_or_a_return",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "sent", "acknowledged", "failed"])
                ),
                name="fiscal_document_status_is_declared",
            ),
        ),
    ]
