"""S6's three enum types, its five tables, and what it migrates onto S4's two.

**Three `CREATE TYPE` and no `ALTER TYPE`** (ownership.md, enum register).
`purchase_order_status` is the ledger's, with its six values declared at
creation; `goods_receipt_type` and `forecast_basis` are coined by this stage on
tables this stage creates, which is what rule 1 covers -- no ledger amendment is
asked for.

**Two things land on S4's tables, and both are rule 4's exception to rule 1.**
An index and a check constraint belong to the stage whose read path or whose
invariant needs them, not to the table's creator:

  * `sales (tenant_id, location_id, occurred_at)` is the forecast job's 26-week
    window scan. It is **not** `sales_location_period`, which is on
    `recorded_at` and is what every rollup reads: a window over one clock cannot
    be served by an index on the other.
  * `sale_lines (tenant_id, item_id, sale_id)` is created here as the item-grain
    superset **S7 inherits**. S6 and S7 run in parallel off S4 and both want an
    item-first index on that table; the lower-numbered stage creates it, because
    a near-duplicate index on the same table costs a second write on every sale
    line, forever, to save one lookup.
  * The `CHECK` on `sales` is what makes the imported-sales quarantine
    construction rather than discipline. S6 is the only writer of `imported`, so
    the constraint that makes `imported` safe is migrated from here: an imported
    row carrying a `shift_id` or a `device_id` is refused **by the database**,
    and it can therefore never reach a turno, a cash reconciliation or a fiscal
    document.

**Nothing here touches `stock_moves`.** The move-history index this stage's
censoring replay reads was created by S3 and is inherited; a second stage
migrating the same columns is a duplicate that fails on a clean build (rule 4).

The RLS policies live in 0016, so the security layer stays one file somebody can
read in SQL -- the same split S0 took between 0001 and 0002, S1 between 0005 and
0006, S2 between 0007 and 0008, S3 between 0009 and 0010, S4 between 0011 and
0012 and S5 between 0013 and 0014.
"""

# Generated by Django 6.1 on 2026-09-04 03:18

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


ENUMS = r"""
-- The ledger's six, declared complete. `discarded` is terminal and is **not a
-- failure**: discarding a suggestion the model made is the product working, and
-- design-system §B.7.4 colours it neutral for exactly that reason.
CREATE TYPE purchase_order_status AS ENUM (
    'suggested',
    'approved',
    'sent',
    'partially_received',
    'received',
    'discarded'
);

-- Coined here. The ledger assigns `supplier_return` moves to S6 and assigns S6
-- no returns table, so a return is a receipt with the sign reversed: the same
-- document, the same lots, the same one call into S3's ledger service.
CREATE TYPE goods_receipt_type AS ENUM ('receipt', 'supplier_return');

-- Coined here: architecture §1's three regimes, decided per item and per sede
-- and never per tenant. It is the column any later surface reads to say which
-- regime a number came from without inferring it from a null.
CREATE TYPE forecast_basis AS ENUM ('parametric', 'learning', 'learned');
"""

ENUMS_REVERSE = r"""
DROP TYPE forecast_basis;
DROP TYPE goods_receipt_type;
DROP TYPE purchase_order_status;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_handoff_rls"),
    ]

    operations = [
        # First, and before any table that names them.
        migrations.RunSQL(sql=ENUMS, reverse_sql=ENUMS_REVERSE),
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekly_sales",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "trend",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "coverage_days",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                ("reorder_point", models.IntegerField(default=0)),
                ("safety_stock", models.IntegerField(default=0)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("model_version", models.CharField(max_length=64)),
                (
                    "basis",
                    core.models.EnumField(
                        choices=[
                            ("parametric", "Sin histórico"),
                            ("learning", "Aprendiendo"),
                            ("learned", "Aprendida"),
                        ],
                        db_enum="forecast_basis",
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                (
                    "usable_weeks",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "variation",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "imported_share",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
            ],
            options={
                "db_table": "demand_forecasts",
                "ordering": ["item__name"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    core.models.EnumField(
                        choices=[
                            ("receipt", "Recepción"),
                            ("supplier_return", "Devolución al proveedor"),
                        ],
                        db_enum="goods_receipt_type",
                        default="receipt",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "En captura"), ("confirmed", "Confirmada")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("received_by_name", models.CharField(blank=True, max_length=200)),
                (
                    "supplier_document_number",
                    models.CharField(blank=True, max_length=64),
                ),
                ("notes", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "goods_receipts",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lot_code", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "goods_receipt_lines",
                "ordering": ["item__name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    core.models.EnumField(
                        choices=[
                            ("suggested", "Sugerida"),
                            ("approved", "Aprobada"),
                            ("sent", "Enviada al proveedor"),
                            ("partially_received", "Recibida parcial"),
                            ("received", "Recibida"),
                            ("discarded", "Descartada"),
                        ],
                        db_enum="purchase_order_status",
                        default="suggested",
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("model", "Propuesta por el modelo"),
                            ("manual", "Escrita a mano"),
                        ],
                        default="model",
                        max_length=16,
                    ),
                ),
                ("model_version", models.CharField(blank=True, max_length=64)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("approved_by_name", models.CharField(blank=True, max_length=200)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("discarded_at", models.DateTimeField(blank=True, null=True)),
                ("dispatch_attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_dispatch_error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "purchase_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("suggested_quantity", models.IntegerField(blank=True, null=True)),
                ("approved_quantity", models.IntegerField(default=0)),
                ("received_quantity", models.IntegerField(default=0)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("reason_code", models.CharField(blank=True, max_length=48)),
                (
                    "basis",
                    core.models.EnumField(
                        blank=True,
                        choices=[
                            ("parametric", "Sin histórico"),
                            ("learning", "Aprendiendo"),
                            ("learned", "Aprendida"),
                        ],
                        db_enum="forecast_basis",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "coverage_days",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_lines",
                "ordering": ["item__name"],
            },
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["tenant", "location", "occurred_at"],
                name="sales_forecast_window",
            ),
        ),
        migrations.AddIndex(
            model_name="saleline",
            index=models.Index(
                fields=["tenant", "item", "sale"], name="sale_lines_item_grain"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "imported"), _negated=True),
                    models.Q(("device__isnull", True), ("shift__isnull", True)),
                    _connector="OR",
                ),
                name="an_imported_sale_has_no_shift_and_no_device",
            ),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipts",
                to="core.supplier",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="goods_receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="core.goodsreceipt",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.lot",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="core.supplier",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="core.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="core.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_lines",
                to="core.purchaseorderline",
            ),
        ),
        migrations.AddIndex(
            model_name="demandforecast",
            index=models.Index(
                fields=["tenant", "location", "item"],
                name="demand_forecasts_by_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandforecast",
            constraint=models.UniqueConstraint(
                fields=("tenant", "item", "location"),
                name="one_forecast_per_item_and_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandforecast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("basis", "parametric"), _negated=True),
                    models.Q(
                        ("coverage_days__isnull", True),
                        ("trend__isnull", True),
                        ("weekly_sales__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="a_parametric_forecast_states_no_demand",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandforecast",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="confidence_is_a_share",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["tenant", "location", "status", "created_at"],
                name="purchase_orders_grid",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "location", "number"),
                name="one_purchase_order_number_per_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["model", "manual"])),
                name="purchase_order_source_is_declared",
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(
                fields=["tenant", "location", "received_at"],
                name="goods_receipts_by_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "confirmed"])),
                name="goods_receipt_status_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type", "receipt"),
                    ("purchase_order__isnull", True),
                    _connector="OR",
                ),
                name="a_supplier_return_has_no_order_behind_it",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "purchase_order", "item"),
                name="one_line_per_item_per_purchase_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reason_code", ""),
                    (
                        "reason_code__in",
                        (
                            "seasonal_peak_recent_stockout",
                            "stable_rotation",
                            "stockout_available_elsewhere",
                            "seasonal_peak",
                            "predictable_chronic",
                            "sufficient_coverage",
                            "lot_expiring",
                            "overstock",
                            "cross_sell_pair",
                            "learning_floor",
                            "parametric_policy",
                            "parametric_category_default",
                            "measured_demand",
                        ),
                    ),
                    _connector="OR",
                ),
                name="purchase_reason_code_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reason", ""), ("basis", "learned"), _connector="OR"
                ),
                name="only_a_learned_line_carries_model_prose",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("approved_quantity__gte", 0)),
                name="an_approved_quantity_is_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="a_receipt_line_moves_something",
            ),
        ),
    ]
