"""S7's five enum types, its two tables, and the one constraint it migrates onto S1's.

**Four `CREATE TYPE` and no `ALTER TYPE`** (ownership.md, enum register).
`price_proposal_status` is the ledger's, with its six values declared at
creation; `elasticity_status`, `no_proposal_reason` and `proposal_basis` are
coined by this stage on tables this stage creates, which is what rule 1 covers.
`cap_status` is the fifth name the stage document coins and is deliberately
**not** a Postgres type: it is written into `items.cap_status`, a `varchar` S1
created empty, and mirrored into `items.custom.pricing` -- a `CREATE TYPE` there
would be S7 migrating a type onto another stage's column.

**One thing lands on S1's table, and it is rule 4's exception to rule 1.**
`item_prices.proposal_id` was created by S1 as a bare `uuid` with the comment
that S7 adds the constraint when it creates `price_proposals`, because the
referenced table did not exist yet. It is added here as raw SQL rather than by
turning the field into a `ForeignKey`: Postgres creates **no index** for the
referencing side of a foreign key, so the constraint costs nothing on a table
every till pulls from -- and rule 4 forbids this stage adding an index to
`item_prices` at all. `ON DELETE RESTRICT` is the honest rule: a proposal is
superseded, never deleted, and a price row that names one must keep naming it.

**Nothing here touches `items`, `sale_lines` or `stock_moves`.** The cap columns
were created by S1; the item-grain sale index was created by S6 as the superset
this stage inherits; the move-history index was created by S3. A second stage
migrating the same columns is a duplicate that fails on a clean build (rule 4).

The RLS policies live in 0018, so the security layer stays one file somebody can
read in SQL -- the same split S0 took between 0001 and 0002 and every stage
since has taken after it.
"""

# Generated by Django 6.1 on 2026-09-04 15:15

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


ENUMS = r"""
-- The ledger's six, declared complete, and the split down the middle is A11:
-- S7 writes `proposed`, `above_cap` and `superseded`; S1's price editor writes
-- `taken`, `modified` and `dismissed`. `approved`, `applied` and `reverted` do
-- not exist -- they went with the write path this stage no longer has.
CREATE TYPE price_proposal_status AS ENUM (
    'proposed',
    'above_cap',
    'taken',
    'modified',
    'dismissed',
    'superseded'
);

-- Coined here. What a row with a null `elasticity` is saying, in six words
-- rather than one: "we could not measure this" and "this reference has no cost
-- loaded" send a reader to two different places.
CREATE TYPE elasticity_status AS ENUM (
    'estimated',
    'insufficient_observations',
    'insufficient_variation',
    'no_sales',
    'no_cost',
    'inactive'
);

-- Coined here. Why an item that **was** evaluated got no proposal anyway. It is
-- separate from `elasticity_status` because the screen has to distinguish *we
-- could not measure this* from *we looked and there is nothing worth doing*.
CREATE TYPE no_proposal_reason AS ENUM (
    'low_confidence',
    'below_materiality',
    'cooldown',
    'cap_blocks_raise',
    'cap_at_current',
    'at_margin_goal',
    'margin_gap_immaterial',
    'elastic_veto'
);

-- Coined here: architecture §1's basis, made a column. Which of the two engines
-- produced a proposal, stamped on every row rather than inferred at read time
-- from whether `elasticity_estimate_id` happens to be null.
CREATE TYPE proposal_basis AS ENUM ('margin_rule', 'elasticity');
"""

ENUMS_REVERSE = r"""
DROP TYPE proposal_basis;
DROP TYPE no_proposal_reason;
DROP TYPE elasticity_status;
DROP TYPE price_proposal_status;
"""

# Rule 4's exception to rule 1, and the promise S1's own model comment made.
# **No index comes with it**: Postgres indexes the referenced side of a foreign
# key and not the referencing one, so this adds a constraint to a table every
# till replicates and not a second write on every price row.
PROPOSAL_FK = r"""
ALTER TABLE item_prices
    ADD CONSTRAINT item_prices_proposal_id_fk
    FOREIGN KEY (proposal_id) REFERENCES price_proposals (id)
    ON DELETE RESTRICT;
"""

PROPOSAL_FK_REVERSE = r"""
ALTER TABLE item_prices DROP CONSTRAINT item_prices_proposal_id_fk;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_purchasing_rls"),
    ]

    operations = [
        # First, and before any table that names them.
        migrations.RunSQL(sql=ENUMS, reverse_sql=ENUMS_REVERSE),
        migrations.CreateModel(
            name="ElasticityEstimate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "elasticity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "r2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("window", models.CharField(max_length=8)),
                ("observations", models.PositiveSmallIntegerField(default=0)),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("model_version", models.CharField(max_length=64)),
                (
                    "status",
                    core.models.EnumField(
                        choices=[
                            ("estimated", "Estimada"),
                            ("insufficient_observations", "Pocas semanas"),
                            ("insufficient_variation", "Sin variación de precio"),
                            ("no_sales", "Sin ventas en la ventana"),
                            ("no_cost", "Sin costo cargado"),
                            ("inactive", "Referencia inactiva"),
                        ],
                        db_enum="elasticity_status",
                        max_length=32,
                    ),
                ),
                (
                    "no_proposal_reason",
                    core.models.EnumField(
                        blank=True,
                        choices=[
                            ("low_confidence", "Estimación de baja confianza"),
                            ("below_materiality", "Impacto por debajo del mínimo"),
                            ("cooldown", "El precio cambió hace poco"),
                            ("cap_blocks_raise", "Sin tope regulado conocido"),
                            ("cap_at_current", "El precio ya está en el tope"),
                            ("at_margin_goal", "Ya está en la meta de margen"),
                            ("margin_gap_immaterial", "La diferencia no alcanza"),
                            ("elastic_veto", "Demanda sensible al precio"),
                        ],
                        db_enum="no_proposal_reason",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "std_error",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "ci_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "ci_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("distinct_prices", models.PositiveSmallIntegerField(default=0)),
                (
                    "price_dispersion",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=8, null=True
                    ),
                ),
                (
                    "weeks_excluded_stockout",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "weeks_excluded_promo",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "imported_share",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "Alta"),
                            ("medium", "Media"),
                            ("low", "Baja"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elasticity_estimates",
                        to="core.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "elasticity_estimates",
                "ordering": ["-computed_at", "item__name"],
            },
        ),
        migrations.CreateModel(
            name="PriceProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "basis",
                    core.models.EnumField(
                        choices=[
                            ("margin_rule", "Meta de margen"),
                            ("elasticity", "Elasticidad"),
                        ],
                        db_enum="proposal_basis",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    core.models.EnumField(
                        choices=[
                            ("proposed", "Propuesta"),
                            ("above_cap", "Sobre el tope regulado"),
                            ("taken", "Tomada"),
                            ("modified", "Modificada"),
                            ("dismissed", "Descartada"),
                            ("superseded", "Reemplazada"),
                        ],
                        db_enum="price_proposal_status",
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "suggested_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "current_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "projected_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "estimated_monthly_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "trailing_monthly_units",
                    models.IntegerField(blank=True, null=True),
                ),
                ("respects_regulated_cap", models.BooleanField(default=False)),
                ("resolved_by_name", models.CharField(blank=True, max_length=200)),
                (
                    "resolved_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "Alta"),
                            ("medium", "Media"),
                            ("low", "Baja"),
                        ],
                        max_length=8,
                    ),
                ),
                ("cost_basis", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cost_source",
                    models.CharField(
                        choices=[
                            ("lots", "Lotes en existencia"),
                            ("supplier", "Lista del proveedor"),
                        ],
                        max_length=16,
                    ),
                ),
                ("step_pct", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "margin_gap_pp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("reason_code", models.CharField(max_length=48)),
                (
                    "regulated_max_price_at_proposal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("model_version", models.CharField(max_length=64)),
                (
                    "elasticity_estimate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="core.elasticityestimate",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_proposals",
                        to="core.item",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "price_proposals",
                "ordering": ["-computed_at", "item__name"],
            },
        ),
        migrations.AddIndex(
            model_name="elasticityestimate",
            index=models.Index(
                fields=["tenant", "item", "computed_at"], name="elasticity_by_item_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="elasticityestimate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "item", "location", "computed_at"),
                name="one_estimate_per_item_grain_and_run",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="elasticityestimate",
            constraint=models.CheckConstraint(
                condition=models.Q(("elasticity", 0), _negated=True),
                name="an_elasticity_is_never_exactly_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="elasticityestimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("elasticity__isnull", False), ("status", "estimated")),
                    models.Q(
                        models.Q(("status", "estimated"), _negated=True),
                        ("elasticity__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="an_estimated_row_carries_an_elasticity",
            ),
        ),
        migrations.AddConstraint(
            model_name="elasticityestimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence", ""),
                    ("confidence__in", ["high", "medium", "low"]),
                    _connector="OR",
                ),
                name="elasticity_confidence_is_declared",
            ),
        ),
        migrations.AddIndex(
            model_name="priceproposal",
            index=models.Index(
                fields=["tenant", "item", "status"], name="price_proposals_by_item"
            ),
        ),
        migrations.AddIndex(
            model_name="priceproposal",
            index=models.Index(
                fields=["tenant", "status", "resolved_at"],
                name="price_proposals_adoption",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("proposed", "above_cap"))),
                fields=("tenant", "item"),
                name="one_live_proposal_per_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason_code__in",
                        (
                            "inelastic_raise",
                            "elastic_reduce",
                            "cap_bound_raise",
                            "margin_below_goal",
                            "above_regulated_cap",
                        ),
                    )
                ),
                name="pricing_reason_code_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__in", ["high", "medium", "low"])),
                name="proposal_confidence_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost_source__in", ["lots", "supplier"])),
                name="proposal_cost_source_is_declared",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("basis", "margin_rule"), _negated=True),
                    ("elasticity_estimate__isnull", True),
                    _connector="OR",
                ),
                name="a_margin_rule_proposal_rests_on_no_estimate",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("resolved_at__isnull", False),
                        ("status__in", ("taken", "modified", "dismissed")),
                    ),
                    models.Q(
                        models.Q(
                            ("status__in", ("taken", "modified", "dismissed")),
                            _negated=True,
                        ),
                        ("resolved_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="a_resolved_proposal_is_dated",
            ),
        ),
        migrations.AddConstraint(
            model_name="priceproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "dismissed"), _negated=True),
                    ("resolved_price__isnull", True),
                    _connector="OR",
                ),
                name="a_dismissal_carries_no_resolved_price",
            ),
        ),
            migrations.RunSQL(
            sql=PROPOSAL_FK, reverse_sql=PROPOSAL_FK_REVERSE
        ),
    ]
